{
 "title": "Tinybird org metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "workspace", "query": { "query": "label_values(workspace)" } },
   { "name": "event", "query": { "query": "label_values(event_type)" } },
   {
    "name": "pipe",
    "query": {
     "query": "label_values({job=\"tinybird_org_metrics\"},pipe)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ingestion rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(workspace, event_type) (rate(ingestion_total{job=\"tinybird_org_metrics\", workspace=~\"$workspace\", event_type=~\"$event\"}[$__rate_interval]))",
     "legendFormat": "{{workspace}}-{{event_type}}"
    }
   ]
  },
  {
   "title": "Ingestion Errors rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum by(workspace, event_type) (rate(ingestion_errors_total{job=\"tinybird_org_metrics\", workspace=~\"$workspace\", event_type=~\"$event\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Ingestion written rows",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(workspace, event_type) (rate(ingestion_written_rows_total{job=\"tinybird_org_metrics\", workspace=~\"$workspace\", event_type=~\"$event\"}[$__rate_interval]))",
     "legendFormat": "{{workspace}}-{{event_type}}"
    }
   ]
  },
  {
   "title": "Ingestion written bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "sum by(workspace, event_type) (rate(ingestion_written_bytes_total{job=\"tinybird_org_metrics\", workspace=~\"$workspace\", event_type=~\"$event\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Ingestion read rows",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(workspace, event_type) (rate(ingestion_read_rows_total{job=\"tinybird_org_metrics\", workspace=~\"$workspace\", event_type=~\"$event\", pipe=~\"$pipe\"}[$__rate_interval]))",
     "legendFormat": "{{workspace}}-{{event_type}}"
    }
   ]
  },
  {
   "title": "Ingestion read bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 19 },
   "targets": [
    {
     "expr": "sum by(workspace, event_type) (rate(ingestion_read_bytes_total{job=\"tinybird_org_metrics\", workspace=~\"$workspace\", event_type=~\"$event\", pipe=~\"$pipe\"}[$__rate_interval]))",
     "legendFormat": "{{workspace}}-{{event_type}}"
    }
   ]
  },
  {
   "title": "Ingestion latency 5m",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum_over_time(ingestion_latency_p99_5m{job=\"tinybird_org_metrics\", workspace=~\"$workspace\", event_type=~\"$event\"}[5m])",
     "legendFormat": "{{workspace}}-p99"
    },
    {
     "expr": "sum_over_time(ingestion_latency_p95_5m{job=\"tinybird_org_metrics\", workspace=~\"$workspace\", event_type=~\"$event\"}[5m])",
     "legendFormat": "{{workspace}}-p95"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 29 },
   "targets": [
    {
     "expr": "storage_rows{job=\"tinybird_org_metrics\", workspace=~\"$workspace\"}",
     "legendFormat": "{{workspace}}-p99"
    }
   ]
  },
  {
   "title": "Jobs success",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "jobs_total{workspace=~\"$workspace\", job=\"tinybird_org_metrics\", status=\"done\"}",
     "legendFormat": "{{workspace}}-{{job_type}}"
    }
   ]
  },
  {
   "title": "Jobs WIP",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 41 },
   "targets": [
    {
     "expr": "jobs_total{workspace=~\"$workspace\", job=\"tinybird_org_metrics\", status=~\"waiting|working\"}",
     "legendFormat": "{{workspace}}-{{job_type}}-{{status}}"
    }
   ]
  },
  {
   "title": "Jobs failed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "jobs_total{workspace=~\"$workspace\", job=\"oa_metrics\", status=\"error\"}",
     "legendFormat": "{{workspace}}-{{job_type}}"
    }
   ]
  },
  {
   "title": "Jobs duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 53 },
   "targets": [
    {
     "expr": "jobs_duration_avg{workspace=~\"$workspace\", job=\"tinybird_org_metrics\"}",
     "legendFormat": "{{workspace}}-{{job_type}}-avg"
    },
    {
     "expr": "jobs_duration_p99{job=\"tinybird_org_metrics\", workspace=~\"$workspace\"}",
     "legendFormat": "{{workspace}}-{{job_type}}-p99"
    }
   ]
  },
  {
   "title": "Pipe endpoints rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum by(workspace, pipe) (rate(requests_views_total{job=\"tinybird_org_metrics\", workspace=~\"$workspace\", pipe=~\"$pipe\"}[$__rate_interval]))",
     "legendFormat": "{{workspace}}-{{pipe}}"
    }
   ]
  },
  {
   "title": "Requests error rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 65 },
   "targets": [
    {
     "expr": "sum by(workspace) (rate(requests_errors_total{job=\"tinybird_org_metrics\", workspace=~\"$workspace\", pipe=~\"$pipe\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Requests read rows",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum by(workspace, pipe) (rate(requests_read_rows_total{job=\"tinybird_org_metrics\", workspace=~\"$workspace\", pipe=~\"$pipe\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Pipe endpoints latency 5m",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 75 },
   "targets": [
    {
     "expr": "sum_over_time(requests_latency_avg_5m{job=\"tinybird_org_metrics\", workspace=~\"$workspace\", pipe=~\"$pipe\"}[5m])",
     "legendFormat": "{{workspace}}-{{pipe}}-p99"
    },
    {
     "expr": "sum_over_time(requests_latency_p99_5m{job=\"tinybird_org_metrics\", workspace=~\"$workspace\", pipe=~\"$pipe\"}[5m])",
     "legendFormat": "{{workspace}}-{{pipe}}-p95"
    }
   ]
  },
  {
   "title": "Requests read bytes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "sum by(workspace, pipe) (rate(requests_read_bytes_total{job=\"tinybird_org_metrics\", workspace=~\"$workspace\", pipe=~\"$pipe\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Requests cpu 5m",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 87 },
   "targets": [
    {
     "expr": "sum_over_time(requests_cpu_time_p99_5m{job=\"tinybird_org_metrics\", workspace=~\"$workspace\", pipe=~\"$pipe\"}[5m])",
     "legendFormat": "{{workspace}}-p99"
    },
    {
     "expr": "sum_over_time(requests_cpu_time_p95_5m{job=\"tinybird_org_metrics\", workspace=~\"$workspace\", pipe=~\"$pipe\"}[5m])",
     "legendFormat": "{{workspace}}-p95"
    }
   ]
  }
 ]
}